/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// parseK6 — parses `k6 run --summary-export <file>` output.
//
// Shape (k6 v1, see testdata/summary.json — generated by
// hack/report-fixtures.sh): {"metrics": {"<name>": {...}}} where trend
// metrics carry avg/min/med/max/p(90)/p(95) (p(99) only when the script
// sets summaryTrendStats), counters carry count/rate and rate metrics
// carry passes/fails/value — for http_req_failed, "passes" counts the
// FAILED requests (the rate's true values).

package report

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
)

type summary struct {
	Metrics map[string]map[string]float64 `json:"metrics"`
}

// Parse maps a k6 summary onto the shared vocabulary. Metrics k6 didn't
// report are omitted, not zeroed.
func parseK6(r io.Reader) (map[string]float64, error) {
	var s summary
	if err := json.NewDecoder(r).Decode(&s); err != nil {
		return nil, fmt.Errorf("k6 summary: %w", err)
	}
	if len(s.Metrics) == 0 {
		return nil, errors.New("k6 summary: no metrics")
	}
	out := map[string]float64{}
	put := func(metric, field, key string) {
		if v, ok := s.Metrics[metric][field]; ok {
			out[key] = v
		}
	}
	put("http_reqs", "count", Requests)
	put("http_reqs", "rate", RPS)
	put("http_req_failed", "passes", Errors)
	put("http_req_failed", "value", ErrorRate)
	put("http_req_duration", "avg", LatencyAvgMs)
	put("http_req_duration", "min", LatencyMinMs)
	put("http_req_duration", "med", LatencyMedMs)
	put("http_req_duration", "p(90)", LatencyP90Ms)
	put("http_req_duration", "p(95)", LatencyP95Ms)
	put("http_req_duration", "p(99)", LatencyP99Ms)
	put("http_req_duration", "max", LatencyMaxMs)
	put("checks", "passes", ChecksPassed)
	put("checks", "fails", ChecksFailed)
	put("iterations", "count", Iterations)
	put("data_received", "count", DataReceivedBytes)
	put("data_sent", "count", DataSentBytes)
	put("vus_max", "max", VUsMax)
	if _, ok := out[ErrorRate]; !ok {
		SetErrorRate(out)
	}
	return out, nil
}
