apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubetest-alt.operator.serviceAccountName" . }}
  labels:
    {{- include "kubetest-alt.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubetest-alt.apiserver.serviceAccountName" . }}
  labels:
    {{- include "kubetest-alt.labels" . | nindent 4 }}
    app.kubernetes.io/component: apiserver
