apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubetest-alt.operator.serviceAccountName" . }}
  labels:
    {{- include "kubetest-alt.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
  {{- with .Values.serviceAccounts.operator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubetest-alt.apiserver.serviceAccountName" . }}
  labels:
    {{- include "kubetest-alt.labels" . | nindent 4 }}
    app.kubernetes.io/component: apiserver
  {{- with .Values.serviceAccounts.apiserver.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
