apiVersion: tests.kubetest.io/v1alpha1
kind: Test
metadata:
  name: sample-gatling
  namespace: default
spec:
  use: [gatling]
  content:
    git:
      uri: https://github.com/kubetest-alt/example-tests.git
      revision: main
  config:
    simulationsFolder:
      type: string
      default: "gatling/user-files/simulations"
    simulation:
      type: string
      default: "example.BasicSimulation"
