apiVersion: tests.kubetest.io/v1alpha1
kind: Test
metadata:
  name: sample-gradle
  namespace: default
spec:
  use: [gradle]
  content:
    git:
      uri: https://github.com/kubetest-alt/example-tests.git
      revision: main
  config:
    projectDir:
      type: string
      default: "gradle"
