apiVersion: tests.kubetest.io/v1alpha1
kind: Test
metadata:
  name: sample-pytest
  namespace: default
spec:
  use: [pytest]
  content:
    git:
      uri: https://github.com/kubetest-alt/example-tests.git
      revision: main
  config:
    testsDir:
      type: string
      default: "pytest"
